
name: CI-CD Pipeline

on:
  push:
    branches:
      - main  # Trigger when code pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Login to Docker Hub using token
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Step 3: Build Docker image (point to repo root)
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce:latest .

    # Step 4: Push Docker image
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce:latest

    # Step 5: Deploy to Kubernetes
    
